export default {
  login: "zainabturkmen",
  id: 132147692,
  node_id: "U_kgDOB-Bp7A",
  avatar_url: "https://avatars.githubusercontent.com/u/132147692?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/zainabturkmen",
  html_url: "https://github.com/zainabturkmen",
  followers_url: "https://api.github.com/users/zainabturkmen/followers",
  following_url:
    "https://api.github.com/users/zainabturkmen/following{/other_user}",
  gists_url: "https://api.github.com/users/zainabturkmen/gists{/gist_id}",
  starred_url:
    "https://api.github.com/users/zainabturkmen/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/zainabturkmen/subscriptions",
  organizations_url: "https://api.github.com/users/zainabturkmen/orgs",
  repos_url: "https://api.github.com/users/zainabturkmen/repos",
  events_url: "https://api.github.com/users/zainabturkmen/events{/privacy}",
  received_events_url:
    "https://api.github.com/users/zainabturkmen/received_events",
  type: "User",
  site_admin: false,
  name: "Zainab Turkmen",
  company: null,
  blog: "",
  location: "Kabul ",
  email: null,
  hireable: null,
  bio: "Hey there! I'm Zainab Turkmen,  a  Frontend Web Developer. Daily coding life!👌\r\nawesome😍😎",
  twitter_username: "ZainabTurkmen",
  public_repos: 78,
  public_gists: 0,
  followers: 42,
  following: 40,
  created_at: "2023-04-29T14:00:39Z",
  updated_at: "2024-05-15T09:59:41Z",
};